-- =============================================
-- Wellbeing Database - Complete Schema Creation Script
-- =============================================
-- This script creates all tables for the Wellbeing application
-- Run this script on a fresh PostgreSQL database
-- =============================================
-- Database: WellbeingDb
-- PostgreSQL Version: 12+
-- =============================================

-- Connect to the database (uncomment if running from psql)
-- \c "WellbeingDb"

-- =============================================
-- Enable required extensions
-- =============================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================
-- 1. Create Clients Table
-- =============================================
CREATE TABLE IF NOT EXISTS "Clients" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(200) NOT NULL,
    "Domain" VARCHAR(255) NOT NULL,
    "InstructionsText" VARCHAR(5000) NOT NULL,
    "ClientSettings" JSONB NOT NULL DEFAULT '{}',
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE NULL,
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE
);

-- Indexes for Clients
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Clients_Domain" ON "Clients" ("Domain");

COMMENT ON TABLE "Clients" IS 'Stores client/company information';
COMMENT ON COLUMN "Clients"."Domain" IS 'Unique domain identifier for the client';
COMMENT ON COLUMN "Clients"."ClientSettings" IS 'JSON configuration settings for the client';

-- =============================================
-- 2. Create AspNetUsers Table
-- =============================================
CREATE TABLE IF NOT EXISTS "AspNetUsers" (
    "Id" UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    "FirstName" VARCHAR(100) NOT NULL,
    "LastName" VARCHAR(100) NOT NULL,
    "UserName" VARCHAR(256) NOT NULL,
    "NormalizedUserName" VARCHAR(256) NOT NULL,
    "Email" VARCHAR(256) NOT NULL,
    "NormalizedEmail" VARCHAR(256) NOT NULL,
    "EmailConfirmed" BOOLEAN NOT NULL DEFAULT FALSE,
    "PasswordHash" TEXT NOT NULL,
    "SecurityStamp" TEXT NOT NULL,
    "ConcurrencyStamp" TEXT NOT NULL,
    "PhoneNumber" VARCHAR(20) NULL,
    "PhoneNumberConfirmed" BOOLEAN NOT NULL DEFAULT FALSE,
    "TwoFactorEnabled" BOOLEAN NOT NULL DEFAULT FALSE,
    "LockoutEnd" TIMESTAMP WITH TIME ZONE NULL,
    "LockoutEnabled" BOOLEAN NOT NULL DEFAULT FALSE,
    "AccessFailedCount" INTEGER NOT NULL DEFAULT 0,
    "IsFirstLogin" BOOLEAN NOT NULL DEFAULT FALSE,
    "RequiresOtpVerification" BOOLEAN NOT NULL DEFAULT FALSE,
    "AuthMethod" VARCHAR(50) NULL,
    "LeadershipLevel" VARCHAR(100) NULL,
    "Tenant" VARCHAR(100) NULL,
    "ClientsId" INTEGER NOT NULL,
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "FK_AspNetUsers_Clients_ClientsId" 
        FOREIGN KEY ("ClientsId") 
        REFERENCES "Clients" ("Id") 
        ON DELETE RESTRICT
);

-- Indexes for AspNetUsers
CREATE INDEX IF NOT EXISTS "IX_AspNetUsers_ClientsId" ON "AspNetUsers" ("ClientsId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_AspNetUsers_NormalizedEmail" ON "AspNetUsers" ("NormalizedEmail");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_AspNetUsers_NormalizedUserName" ON "AspNetUsers" ("NormalizedUserName");

COMMENT ON TABLE "AspNetUsers" IS 'Stores user accounts and authentication information';
COMMENT ON COLUMN "AspNetUsers"."NormalizedEmail" IS 'Normalized email for case-insensitive lookups';
COMMENT ON COLUMN "AspNetUsers"."NormalizedUserName" IS 'Normalized username for case-insensitive lookups';

-- =============================================
-- 3. Create Surveys Table
-- =============================================
CREATE TABLE IF NOT EXISTS "Surveys" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" VARCHAR(500) NOT NULL,
    "Description" VARCHAR(2000) NULL,
    "ClientsId" INTEGER NOT NULL,
    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "StartDate" TIMESTAMP WITH TIME ZONE NULL,
    "EndDate" TIMESTAMP WITH TIME ZONE NULL,
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE NULL,
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "FK_Surveys_Clients_ClientsId" 
        FOREIGN KEY ("ClientsId") 
        REFERENCES "Clients" ("Id") 
        ON DELETE RESTRICT
);

-- Indexes for Surveys
CREATE INDEX IF NOT EXISTS "IX_Surveys_ClientsId" ON "Surveys" ("ClientsId");
CREATE INDEX IF NOT EXISTS "IX_Surveys_IsActive_IsDeleted" ON "Surveys" ("IsActive", "IsDeleted") WHERE "IsDeleted" = FALSE;

COMMENT ON TABLE "Surveys" IS 'Stores survey information linked to clients';
COMMENT ON COLUMN "Surveys"."IsActive" IS 'Whether the survey is currently active and accepting responses';

-- =============================================
-- 4. Create WellbeingDimensions Table
-- =============================================
CREATE TABLE IF NOT EXISTS "WellbeingDimensions" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(200) NOT NULL,
    "Description" VARCHAR(1000) NULL,
    "ClientsId" INTEGER NOT NULL,
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE NULL,
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "FK_WellbeingDimensions_Clients_ClientsId" 
        FOREIGN KEY ("ClientsId") 
        REFERENCES "Clients" ("Id") 
        ON DELETE RESTRICT
);

-- Indexes for WellbeingDimensions
CREATE INDEX IF NOT EXISTS "IX_WellbeingDimensions_ClientsId" ON "WellbeingDimensions" ("ClientsId");

COMMENT ON TABLE "WellbeingDimensions" IS 'Stores wellbeing dimension categories';
COMMENT ON COLUMN "WellbeingDimensions"."Name" IS 'Name of the wellbeing dimension (e.g., Physical, Mental, Social)';

-- =============================================
-- 5. Create WellbeingSubDimensions Table
-- =============================================
CREATE TABLE IF NOT EXISTS "WellbeingSubDimensions" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(200) NOT NULL,
    "Description" VARCHAR(1000) NULL,
    "WellbeingDimensionId" INTEGER NOT NULL,
    "ClientsId" INTEGER NOT NULL,
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE NULL,
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "FK_WellbeingSubDimensions_WellbeingDimensions_WellbeingDimensionId" 
        FOREIGN KEY ("WellbeingDimensionId") 
        REFERENCES "WellbeingDimensions" ("Id") 
        ON DELETE RESTRICT,
    CONSTRAINT "FK_WellbeingSubDimensions_Clients_ClientsId" 
        FOREIGN KEY ("ClientsId") 
        REFERENCES "Clients" ("Id") 
        ON DELETE RESTRICT
);

-- Indexes for WellbeingSubDimensions
CREATE INDEX IF NOT EXISTS "IX_WellbeingSubDimensions_WellbeingDimensionId" ON "WellbeingSubDimensions" ("WellbeingDimensionId");
CREATE INDEX IF NOT EXISTS "IX_WellbeingSubDimensions_ClientsId" ON "WellbeingSubDimensions" ("ClientsId");

COMMENT ON TABLE "WellbeingSubDimensions" IS 'Stores sub-dimensions within wellbeing dimensions';
COMMENT ON COLUMN "WellbeingSubDimensions"."WellbeingDimensionId" IS 'Parent wellbeing dimension';

-- =============================================
-- 6. Create Questions Table
-- =============================================
CREATE TABLE IF NOT EXISTS "Questions" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "QuestionText" VARCHAR(2000) NOT NULL,
    "QuestionType" VARCHAR(50) NULL,
    "SurveyId" INTEGER NOT NULL,
    "ClientsId" INTEGER NOT NULL,
    "QuestionConfig" JSONB NULL,
    "IsRequired" BOOLEAN NOT NULL DEFAULT TRUE,
    "DisplayOrder" INTEGER NOT NULL DEFAULT 0,
    "WellbeingDimensionId" INTEGER NULL,
    "WellbeingSubDimensionId" INTEGER NULL,
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE NULL,
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "FK_Questions_Surveys_SurveyId" 
        FOREIGN KEY ("SurveyId") 
        REFERENCES "Surveys" ("Id") 
        ON DELETE RESTRICT,
    CONSTRAINT "FK_Questions_Clients_ClientsId" 
        FOREIGN KEY ("ClientsId") 
        REFERENCES "Clients" ("Id") 
        ON DELETE RESTRICT,
    CONSTRAINT "FK_Questions_WellbeingDimensions_WellbeingDimensionId" 
        FOREIGN KEY ("WellbeingDimensionId") 
        REFERENCES "WellbeingDimensions" ("Id") 
        ON DELETE RESTRICT,
    CONSTRAINT "FK_Questions_WellbeingSubDimensions_WellbeingSubDimensionId" 
        FOREIGN KEY ("WellbeingSubDimensionId") 
        REFERENCES "WellbeingSubDimensions" ("Id") 
        ON DELETE RESTRICT
);

-- Indexes for Questions
CREATE INDEX IF NOT EXISTS "IX_Questions_SurveyId" ON "Questions" ("SurveyId");
CREATE INDEX IF NOT EXISTS "IX_Questions_ClientsId" ON "Questions" ("ClientsId");
CREATE INDEX IF NOT EXISTS "IX_Questions_SurveyId_DisplayOrder" ON "Questions" ("SurveyId", "DisplayOrder");
CREATE INDEX IF NOT EXISTS "IX_Questions_WellbeingDimensionId" ON "Questions" ("WellbeingDimensionId");
CREATE INDEX IF NOT EXISTS "IX_Questions_WellbeingSubDimensionId" ON "Questions" ("WellbeingSubDimensionId");

COMMENT ON TABLE "Questions" IS 'Stores survey questions';
COMMENT ON COLUMN "Questions"."QuestionText" IS 'The question text displayed to users';
COMMENT ON COLUMN "Questions"."QuestionConfig" IS 'JSON configuration for question components (rating, checkbox, etc.)';
COMMENT ON COLUMN "Questions"."DisplayOrder" IS 'Order in which questions appear in the survey';
COMMENT ON COLUMN "Questions"."WellbeingDimensionId" IS 'Optional link to wellbeing dimension (for backward compatibility)';
COMMENT ON COLUMN "Questions"."WellbeingSubDimensionId" IS 'Optional link to wellbeing sub-dimension (for backward compatibility)';

-- =============================================
-- 7. Create QuestionResponses Table
-- =============================================
CREATE TABLE IF NOT EXISTS "QuestionResponses" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "QuestionId" INTEGER NOT NULL,
    "AspNetUsersId" UUID NOT NULL,
    "ClientsId" INTEGER NOT NULL,
    "ComponentType" VARCHAR(50) NOT NULL,
    "ComponentIndex" INTEGER NOT NULL DEFAULT 0,
    "ResponseValue" JSONB NOT NULL,
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE NULL,
    "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "FK_QuestionResponses_Questions_QuestionId" 
        FOREIGN KEY ("QuestionId") 
        REFERENCES "Questions" ("Id") 
        ON DELETE RESTRICT,
    CONSTRAINT "FK_QuestionResponses_AspNetUsers_AspNetUsersId" 
        FOREIGN KEY ("AspNetUsersId") 
        REFERENCES "AspNetUsers" ("Id") 
        ON DELETE RESTRICT,
    CONSTRAINT "FK_QuestionResponses_Clients_ClientsId" 
        FOREIGN KEY ("ClientsId") 
        REFERENCES "Clients" ("Id") 
        ON DELETE RESTRICT
);

-- Indexes for QuestionResponses
CREATE INDEX IF NOT EXISTS "IX_QuestionResponses_QuestionId" ON "QuestionResponses" ("QuestionId");
CREATE INDEX IF NOT EXISTS "IX_QuestionResponses_AspNetUsersId" ON "QuestionResponses" ("AspNetUsersId");
CREATE INDEX IF NOT EXISTS "IX_QuestionResponses_ClientsId" ON "QuestionResponses" ("ClientsId");
CREATE INDEX IF NOT EXISTS "IX_QuestionResponses_ComponentType" ON "QuestionResponses" ("ComponentType");
CREATE INDEX IF NOT EXISTS "IX_QuestionResponses_AspNetUsersId_QuestionId_IsDeleted" 
    ON "QuestionResponses" ("AspNetUsersId", "QuestionId", "IsDeleted") 
    WHERE "IsDeleted" = FALSE;

COMMENT ON TABLE "QuestionResponses" IS 'Stores user responses to question components';
COMMENT ON COLUMN "QuestionResponses"."ComponentType" IS 'Type of component (rating, checkbox_group, dropdown, comment)';
COMMENT ON COLUMN "QuestionResponses"."ComponentIndex" IS 'Index of the component within the question (0-based)';
COMMENT ON COLUMN "QuestionResponses"."ResponseValue" IS 'JSON value of the response (number for rating, array for checkbox, string for dropdown/comment)';

-- =============================================
-- Verification Queries
-- =============================================
DO $$
BEGIN
    RAISE NOTICE '=============================================';
    RAISE NOTICE 'Database schema created successfully!';
    RAISE NOTICE '=============================================';
    RAISE NOTICE 'Tables created:';
    RAISE NOTICE '  - Clients';
    RAISE NOTICE '  - AspNetUsers';
    RAISE NOTICE '  - Surveys';
    RAISE NOTICE '  - WellbeingDimensions';
    RAISE NOTICE '  - WellbeingSubDimensions';
    RAISE NOTICE '  - Questions';
    RAISE NOTICE '  - QuestionResponses';
    RAISE NOTICE '=============================================';
END $$;

-- List all created tables with column counts
SELECT 
    table_name AS "Table Name",
    (SELECT COUNT(*) FROM information_schema.columns 
     WHERE table_schema = 'public' 
     AND table_name = t.table_name) AS "Column Count"
FROM information_schema.tables t
WHERE table_schema = 'public' 
    AND table_type = 'BASE TABLE'
    AND table_name IN (
        'Clients', 
        'AspNetUsers', 
        'Surveys', 
        'WellbeingDimensions', 
        'WellbeingSubDimensions', 
        'Questions', 
        'QuestionResponses'
    )
ORDER BY 
    CASE table_name
        WHEN 'Clients' THEN 1
        WHEN 'AspNetUsers' THEN 2
        WHEN 'Surveys' THEN 3
        WHEN 'WellbeingDimensions' THEN 4
        WHEN 'WellbeingSubDimensions' THEN 5
        WHEN 'Questions' THEN 6
        WHEN 'QuestionResponses' THEN 7
    END;

-- =============================================
-- End of Script
-- =============================================
